# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[douyin-server]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

file:
  video-output: /home/files/videos/
  image-output: /home/files/images/