# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[douyin-server]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

file:
  video-output: /home/files/videos/
  image-output: /home/files/images/

redis:
  addr: '120.25.153.110'
  port: '6379'
  password: 'austin'
  db: '0'
  poolsize: '100'