# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[douyin-server]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

file:
  video-output: /home/files/videos/
  image-output: /home/files/images/

redis:
  addr: '127.0.0.1'
  port: '6379'
  password: '123456'
  db: '0'
  poolsize: '100'


mysql:
  path: '127.0.0.1'
  port: '3306'
  config: 'charset=utf8mb4&parseTime=True'
  db-name: 'douyin'
  username: 'root'
  password: '123456'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

jwt:
  signing-key: '123456'
  expires-time: 604800
  issuer: '123456'