# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[douyin-server]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

file:
  video-output: /home/files/videos/
  image-output: /home/files/images/
#  jtan's local test directory
#  video-output: C:\Users\jtan\Desktop\douyin-backend\
#  image-output: C:\Users\jtan\Desktop\douyin-backend\

redis:
  addr: '220.243.147.162'
  port: '6379'
  password: '220429douyin'
  db: '0'
  poolsize: '100'


mysql:
  path: '220.243.147.162'
  port: '3306'
  config: 'charset=utf8mb4&parseTime=True'
  db-name: 'douyin'
  username: 'root'
  password: '220429douyin'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

jwt:
  signing-key: '220429douyin'
  expires-time: 604800
  issuer: 'sota'