# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[douyin-server]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

file:
  video-output: your video path
  image-output: your image path

redis:
  addr: '127.0.0.1'
  port: '6379'
  password: ''
  db: '0'
  poolsize: '100'


mysql:
  path: '127.0.0.1'
  port: '3306'
  config: ''
  db-name: ''
  username: 'root'
  password: ''
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

jwt:
  signing-key: ''
  expires-time: 10
  issuer: ''