# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[douyin-server]'
  director: 'log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

file:
  video-output: /home/files/videos/
  image-output: /home/files/images/
#  jtan's local test directory
#  video-output: C:\Users\jtan\Desktop\douyin-backend\
#  image-output: C:\Users\jtan\Desktop\douyin-backend\

redis:
  addr: ''
  port: '6379'
  password: ''
  db: '0'
  poolsize: '100'


mysql:
  path: ''
  port: '3306'
  config: 'charset=utf8mb4&parseTime=True'
  db-name: ''
  username: ''
  password: ''
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

jwt:
  signing-key: ''
  expires-time: 604800
  issuer: ''